### ISSUE TITLE
ResourceFactory global resource pool 

### ISSUE THREAD

**Issue by markst** [wvteijlingen/Spine#102]
I suppose this is related to #17 
I'm trying to use a global resource pool so that objects are reused throughout the entire lifetime of Spine. 

I wonder if you have any advice as to implementing this?

**Comment by wvteijlingen** [comment]
Not particularly. I've been out of this project for some time so for the top of my head I wouldn't know the exact scope of implementing this.

The hardest thing I think is keeping the relationships up to date.  For example, you have a resource "Foo:1" in the pool that points to resource "Bar:2". Now if you later fetch "Bar:2", you'd have to update the relationship in "Foo:1".

**Comment by wvteijlingen** [comment]
I'm closing this beacause it's not a direct issue with Spine.
