### ISSUE TITLE
No way to act on a resource being saved

### ISSUE THREAD

**Issue by Cbieniak** [wvteijlingen/Spine#122]
Currently we have a situation where we want to persist an objects data to keychain if it has a authtoken, but we don't have an attribute that is called on completion of the mapping of values.

I was wondering if you saw this action a responsibility of the future. Possibly with all Resources conforming to a didFinishMapping protocol and the success future calling it. Or a resource responsibility where it keeps track itself and acts once it knows all attributes have been mapped.

**Comment by wvteijlingen** [comment]
When the `onSuccess` callback fires, mapping of values has finished. But I guess you mean some callbacks in the Resource class itself. I've thought about adding that at some point, but never really had a use case for it myself yet.

Perhaps in the meantime you can use Key Value Observing to achieve this in the meantime.

**Comment by Cbieniak** [comment]
thank you for the reply.

We've decided to manually do these actions on specific endpoints and it turns out having it as a callback would have probably been overkill anyway.

**Comment by wvteijlingen** [comment]
Good to hear this is solved for you :).
