### ISSUE TITLE
Serialize error for array of Doubles

### ISSUE THREAD

**Issue by garySWARM** [wvteijlingen/Spine#125]
Hi, the latest version of the library is corrupting a location value, which is defined as:
var location : [Double]?
and should be serialized as "location":[-73.9599,40.72087]
instead, this field serializes as
"location":"(\n    \"-73.9599\",\n    \"40.72087\"\n)"

Help please!
Thanks!
 - Gary

**Comment by wvteijlingen** [comment]
What Swift version are you using?

**Comment by garySWARM** [comment]
I just converted to Swift 3.0

**Comment by wvteijlingen** [comment]
Could you try if this works correctly when using an NSArray?

**Comment by garySWARM** [comment]
I just changed the type of location to:
    var location : NSArray?
and the serializer gives the same result

**Comment by wvteijlingen** [comment]
This was because the value formatters defaulted to the string representation when no suitable formatter was found. I removed this, and this should work properly now.
