### ISSUE TITLE
JSON API is agnostic about filter strategies, and so should Spine be

### ISSUE THREAD

**Issue by davidstosik** [wvteijlingen/Spine#129]
Hello,

According to the [specification](http://jsonapi.org/format/#fetching-filtering),

> JSON API is agnostic about the strategies supported by a server. The filter query parameter can be used as the basis for any number of filtering strategies.

Recently, it looks like `Query` lost public methods such as [`filterOn`](https://github.com/wvteijlingen/Spine/commit/13c650d66d59f7404905ba6df765a5e5174dbf26#diff-b489b8381789a15170f780b7937d8736L245) and [`addPredicateWithKey`](https://github.com/wvteijlingen/Spine/commit/13c650d66d59f7404905ba6df765a5e5174dbf26#diff-b489b8381789a15170f780b7937d8736R137) (no explicit access level, thus `internal`) that allowed someone to filter a query on something that is not an attribute.
For example, our JSON API implementation defines a filter named `my_stream`, and the results will be filtered to contain items that pertain to the user's stream, but `my_stream` is actually not an attribute on any of our resources.

Is there another way that I'm missing, to build a query with a filter on a keyword that is not an attribute, or did Spine indeed lose that feature? If so, according to the specification, wouldn't it make sense to restore something?

Also see #83 and #84.

**Comment by Ybrin** [comment]
I'll try to fix this and open a pull request. There should not be a restriction about the filters...

**Comment by wvteijlingen** [comment]
Sorry about the delay on this. I've been quite busy and this got lost in my inbox.

You're totally right, this should be fixed. I think this can be fixed quite swiftly by making `addPredicateWithKey` and `addPredicateWithField` public.

Then you can use the `whereAttubute` methods for most basic uses cases, and add custom predicates for more complex filtering.

**Comment by davidstosik** [comment]
Thanks!
