### ISSUE TITLE
format() and unformat() could return Any instead of AnyObject

### ISSUE THREAD

**Issue by Blackjacx** [wvteijlingen/Spine#135]
If ValueFormatter's functions `format()` and `unformat()` would return `Any` instead of `AnyObject` I could write a ValueFormatter that transforms a dictionary of latitude and longitude to a `CLLocationCoordinate2D`  struct. Now I am forced to convert it to `CLLocation` object which means unnecessary overhead. 

I'm sure there are more advantages to this.

**Comment by wvteijlingen** [comment]
That would be a nice update to the current system. Unfortunately Spine currently uses KVC to get and set values on resource objects. This means that we can only use it with reference types afaik.
