### ISSUE TITLE
Problem in implementing login API through apine

### ISSUE THREAD

**Issue by jjangir610** [wvteijlingen/Spine#141]
Hey, I am very new to Spine, and I used in my project and successfully implemented all GET requests. But I am not able to implement this login API to my application.. can anyone please suggest how to do it.

curl -X POST -H "User-Agent: null" -H "X-API-KEY: 76AdER4uJwasgbEbaMyV" -H "Content-Type: application/json" -H "Accept: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: 2fbde0af-c7cd-fd71-0684-cb1afcedfcd4" -d '{
    "data": {
        "type": "user.user",
        "attributes": {
            "firstname": "Harry",
            "lastname": "Potter",
            "email_address": "Harry@Potter.com",
            "password": "123456",
            "password_confirm": "123456",
            "gender": "m",
            "accept_policy": "1"
            
        }
    }
}' "http://xxx.com/api/user/auth/register"

**Comment by wvteijlingen** [comment]
Sorry, I have no idea what you mean. This also doesn't seem to be an issue with the Spine library, so I will close this. Perhaps you can open an issue on Stackoverflow.
