### ISSUE TITLE
Couldn't compile it.

### ISSUE THREAD

**Issue by sachin-sat** [wvteijlingen/Spine#145]
It says that "Module compiled with Swift 3.0 cannot be imported in Swift 3.0.2" .
What should i do?

**Comment by sachin-sat** [comment]
it happens while updating carthage(platform iOS)

CompileSwift normal arm64
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler

**Comment by sachin-sat** [comment]
It seems that Some of the frameworks(BrightFuture, Result) are compiled in Swift 3.0.2
and some(Spine and SwiftyJson) are complied in Swift 3.0.

So i can't use either xcode 8 or 8.2.1. :-(

**Comment by wvteijlingen** [comment]
I don't think this is a problem with Spine itself. If you use Carthage, make sure you update and rebuild te packages. Best thing would be to use the `--no-use-binaries` flag to make sure they are compiled for the correct Swift version.
