### ISSUE TITLE
Server does not receive attributes on save()

### ISSUE THREAD

**Issue by PanagiotisVakalis** [wvteijlingen/Spine#160]
I have created a class, which inherits from the Resource class. This class contains Strings, Dates, other resource objects and LinkedResourceCollection objects.

I have created an initialiser for this class using optional values as parameters.

I am trying to POST a resource using:

    var resource = ResourceName()
    resource.attributeName = "123"

    spine.save(resource).onSuccess { (resource) in
           print("Saved")
    }.onFailure { (error) in
           dump(error)
    }

Although the server gets my request, it does not receive any string containing from the value of the attributeName.

I have copied the JSON which is being created through the debugger and I performed the request through the Postman which did the POST successfully.

**Comment by wvteijlingen** [comment]
Can you post the resource class?

**Comment by PanagiotisVakalis** [comment]
@wvteijlingen  thank you for your answer.

    import Foundation
    import Spine

class Ticket: Resource {
    
    // MARK: - Variables
    var code: String?
    var subject: String?
    var createdDate: Date?
    var updatedDate: Date?
    var requester: User?
    var assignees: LinkedResourceCollection?
    var watchers: LinkedResourceCollection?
    var queue: Queue?
    var group: Group?
    var requestType: RequestType?
    var priority: Priority?
    var status: Status?
    var comments: LinkedResourceCollection?
    
    /*
    let details: [String: Any]! // Field name: field value
    let detailsType: [String: String]! // Field name: field type
    let availableOptions: [String: [String]]? // Field name: options for the pickers
     */
    
    // MARK: - Initializers
    init(ofType type: String?, withCode code: String?, andSubject subject: String?, createdOn created: Date?, andUpdatedOn updated: Date?, requestedBy requester: User?, assignedTo assignees: LinkedResourceCollection?, watchedFrom watchers: LinkedResourceCollection?, inQueue queue: Queue?, andInGroup group: Group?, havingRequestType rType: RequestType?, andPriority priority: Priority?, inStatus status: Status?, containingComments comments: LinkedResourceCollection?) {
        super.init()
        
        self.code = code
        self.subject = subject
        self.createdDate = created
        self.updatedDate = updated
        self.requester = requester
        self.assignees = assignees
        self.watchers = watchers
        self.queue = queue
        self.group = group
        self.requestType = rType
        self.priority = priority
        self.status = status
        self.comments = comments
    }
    
    required init() {
        super.init()
    }
    
    required init(coder: NSCoder) {
        super.init(coder: coder)
    }
    
    // MARK: - Resource functions
    override class var resourceType: ResourceType {
        return "tickets"
    }
    
    
    override class var fields: [Field] {
        
        return fieldsFromDictionary([
            "code": Attribute().readOnly(),
            "subject": StringAttribute(),
            "createdDate": DateAttribute().serializeAs("created_at").readOnly(),
            "updatedDate": DateAttribute().serializeAs("updated_at").readOnly(),
            "comments": ToManyRelationship(Comment.self),
            "requester": ToOneRelationship(User.self),
            "assignees": ToManyRelationship(Agent.self),
            "watchers": ToManyRelationship(User.self),
            "queue": ToOneRelationship(Queue.self),
            "group": ToOneRelationship(Group.self),
            "requestType": ToOneRelationship(RequestType.self),
            "priority": ToOneRelationship(Priority.self),
            "status": ToOneRelationship(Status.self)
        ])
        
    }
    
}

**Comment by PanagiotisVakalis** [comment]
I managed to send the attributes. It wasn't a library's problem but a bug on the server and a typo on the content type
