### ISSUE TITLE
POST one type of resource, receive a different type in response

### ISSUE THREAD

**Issue by alextov** [wvteijlingen/Spine#176]
Hello,

Suppose I have the following API. When user logs in, I'm sending a `POST /auth/sessions` request with the following payload:
```json
{
  "data": {
    "type": "sessions",
    "id": null,
    "attributes": {
      "email": "johndoe@example.com",
      "password": "aardvark"
    }
  }
}
```

In response, the server sends me a `users` resource:
```json
{
  "data": {
    "id": "1234",
    "type": "users",
    "attributes": {
      "email": "johndoe@example.com",
      "about": "About Me",
      "profile_image": null
    }
  }
}
```

I have studied the JSON API specification and couldn't find anything that would suggest that it's prohibited. However, Spine doesn't seem to support such configuration. Am I missing something? I would appreciate any help!

**Comment by markst** [comment]
@alextov https://github.com/wvteijlingen/Spine/issues/93#issuecomment-242754289

**Comment by alextov** [comment]
@markst Thanks for the explanation.
