### ISSUE TITLE
Assign extractedMeta to MetaHoldable resource

### ISSUE THREAD

**Issue by aganov** [wvteijlingen/Spine#19]
I'm not 100% sure about this, but I think it will be right to set `extractedMeta` to `(resource as! MetaHoldable).meta` instead of`representation["meta"]`, since http://jsonapi.org/format/#document-meta is defined in root object, not in the document itself? 

https://github.com/wvteijlingen/Spine/blob/master/Spine/DeserializeOperation.swift#L161

**Comment by wvteijlingen** [comment]
Thanks for raising the issue! Actually I think this is correct. `resource.meta` is for metadata of the resource itself. This is [defined in the spec](http://jsonapi.org/format/#document-resource-objects) as:

> In addition, a resource object MAY contain any of these top-level members:
> - (...)
> - `meta`: a meta object containing non-standard meta-information about a resource that can not be represented as an attribute or relationship.

The `extractedMeta` variable is for top level document meta you refer to.

**Comment by aganov** [comment]
Thank you for response, but now, another question came out, how to access `meta` attribute with `spine.findOne` or `spine.find` method when for example I have document like this?

```json
{
  "meta": {
    "copyright": "Copyright 2015 Example Corp."
  },
  "data": {
    "type": "posts",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    }
  }
}
```

**Comment by wvteijlingen** [comment]
Meta is actually half implemented at this point, my apologies.

The deserializer parses it and sets on the resulting `JSONAPIDocument` struct, but it is not passed back to the find methods. If you want to finish this, it needs to be exposed from the `FetchOperation` result variable, and then passed back in the promise from the find methods.

It might be a good time to decide on what to return from a FetchOperation. Right now it's a `ResourceCollection`, but for this it might need to become a `(ResourceCollection, NSDictionary)` or maybe even a whole `JSONAPIDocument `.

**Comment by aganov** [comment]
Yes, I've traced the meta to `FetchOperation`, but stuck wondering what is the right container for the meta... We can return `JSONAPIDocument` for now, and then assign "primaryMeta" to `collection` or `resource` in `find` / `findOne` methods. Also I think we should move `collectionFromDocument` to `Spine.swift` too...

**Comment by wvteijlingen** [comment]
Support for this has been added in the swift-2.0 branch (#36). The find methods now return a tuple containing the resource(s), contents of top level `meta`, contents of top level `jsonapi` object.
