### ISSUE TITLE
JSONAPIDocument public

### ISSUE THREAD

**Issue by ratzr15** [wvteijlingen/Spine#202]
The public init method is not accessible;

due to: 

**ResourceCollection** initializer is inaccessible due to 'internal' protection level

Can we make it public?

`public init(document: JSONAPIDocument) { 
}
`

**Comment by wvteijlingen** [comment]
I'm not maintaining this library anymore. The project that used this was shelved and I'm too busy with other work, so I cannot afford to spend time on this anymore.

The community is continuing development of Spine at jsonapi-ios/Spine. Feel free to use that fork, and submit pull-requests or open issues there.
