### ISSUE TITLE
Attributes not being serialized on save()

### ISSUE THREAD

**Issue by kurko** [wvteijlingen/Spine#21]
I'm experiencing a problem. Once I instantiate a resource and call `spine.save(user)`, the `attributes` object is not sent to my server (`POST /users`). The full details are below, under _code_.

I'm beginner in iOS dev, so I'm trying to look at Spine's source code to figure out what could be causing it. I realized there are zero tests covering the `save()` method (I could be totally wrong, too). Once you help me out with this, I'd love to open a PR to add some documentation. There's none on how to set attributes (e.g `user.setValue("Alex2", forField: "name")`).

**The code**

```swift
import Spine

class UserResource: Resource {
    dynamic var name: String?
    dynamic var email: String?
    
    override class var resourceType: String {
        return "users"
    }
    
    var fields: [Field] {
        return fieldsFromDictionary([
            "name": Attribute(),
            "email": Attribute()
        ])
    }
}

// in another place, when I hit a button
let baseURL = NSURL(string: "http://localhost:3000/")
let spine = Spine(baseURL: baseURL!)
spine.registerResource(UserResource.resourceType)  { UserResource() }
        
var user = UserResource()
user.name = "Alex"
user.email = "me@mysite.com"
        
println(user.name) // outputs "Alex"
spine.save(user)
```

My server gets

```
{"data"=>{"type"=>"users"}}
```

**The problem**

It's not sending the `attributes` it should.

**Comment by wvteijlingen** [comment]
I updated the SerializeOperation to work with the new `attributes` and `relationships` bags. I don't think that solves your bug though. I don't see anything blatantly wrong with your code.

I also added debug logging to the serialize operation. You can enable this with: `Spine.setLogLevel(.Debug, forDomain: .Serializing)`. Try that and you should see several log messages as follows:

```
❔ Debug   - Serializing resource users(nil, nil) of type 'foos' with id 'nil'
❔ Debug   - Serializing attribute Spine.Attribute with name 'name' as 'name'
❔ Debug   - Serializing attribute Spine.Attribute with name 'email' as 'email'
```

**Comment by kurko** [comment]
Nice. The only message I got was

> ❌ Error   - Cannot deserialize: The given JSON is not a dictionary (hash).

I'll try tweaking things around tonight (after work) and see what could be the issue. At least I have some clue now.

_p.s. regarding the `fields` attribute in `UserResource`, I can't use `override` or that will blow saying there's nothing to override there. Perhaps that's an error because of Swift 1.2 and `fields` is not actually overriding as it should, therefore not returning an expected dictionary/JSON/something?._

**Comment by wvteijlingen** [comment]
Ah, I see where the error lies. It actually stems from an error in the Readme, whoops. Each resource has a class variable called `fields`. This must be overridden in your subclasses. The base `Resource` class returns an empty array. The Readme didn't include the `class` keyword, so you never actually overrode that base method. Therefore, Spine got an empty array for `fields` and didn't serialize anything.

I've updated the Readme and added the `class` keyword.

**Comment by kurko** [comment]
Did a quick test and it at least sends the attributes, but not nested within `attributes`. Check it out:

```
{"data"=>{"email"=>"my@website", "name"=>"Alex", "type"=>"users"}}
```

I'm using master... Any ideas?

**Comment by wvteijlingen** [comment]
Hmm, I added the `attributes` hash yesterday. Are you sure you're using the latest version of master?

**Comment by kurko** [comment]
Right, it's working now then. I'm working on writing some tests... also, even when I return 400 form my server, the block `.onSuccess` is called, which is a major problem.
