### ISSUE TITLE
Cannot invoke 'onSuccess' with an argument list of type '(() -> _)'

### ISSUE THREAD

**Issue by kurko** [wvteijlingen/Spine#22]
I'm getting the following error

<img width="615" alt="screen shot 2015-07-16 at 12 10 50 am" src="https://cloud.githubusercontent.com/assets/70312/8714839/1558e748-2b50-11e5-8992-b91c03b091f1.png">

Here's the code:

```
let baseURL = NSURL(string: "http://localhost:3000/")
let spine = Spine(baseURL: baseURL!)
spine.registerResource(UserResource.resourceType)  { UserResource() }

var user = UserResource()
user.name = "Alex"

spine.save(user).onSuccess {
  println("saved")
}
```

<img width="642" alt="screen shot 2015-07-16 at 12 19 58 am" src="https://cloud.githubusercontent.com/assets/70312/8714866/6e17c35e-2b50-11e5-9f76-7d336eec23b5.png">

Any idea how to fix that?

**Comment by kurko** [comment]
So, I researched and figured out this was seemingly solved in BrightFutures 2.0. However, Spine requires 1.0.1 (I tried adding 2.0 in my Podfile and got this):

```
[!] Unable to satisfy the following requirements:

- `BrightFutures (~> 2.0.1)` required by `Podfile`
- `BrightFutures (~> 1.0.1)` required by `Spine (0.1)`
```

**Comment by wvteijlingen** [comment]
This error is raised because the `onSuccess` callback takes one parameter, the resource that was saved. Change your code as follows to make it work:

```swift
spine.save(user).onSuccess { savedUser in
  println("saved")
}
```

**Comment by kurko** [comment]
Works! I'll leave it open and tonight I'll update the docs. I see it as an issue until we update the docs :smile:

**Comment by wvteijlingen** [comment]
I updated the Readme to include this parameter in the save callback. I used an underscore which means to 'discard' this parameter. It is not needed since you already have a reference to your user, in your case `user`.
