### ISSUE TITLE
NSURLSession not setting 'error'

### ISSUE THREAD

**Issue by kurko** [wvteijlingen/Spine#27]
In the lib tests, the mock library is setting the Error just fine, therefore `onFailure` is triggered correctly.

However, in my own app, the `error` value from a request is never set, even if the status code is 4xx. Check this out:

<img width="709" alt="screen shot 2015-07-18 at 2 54 22 pm" src="https://cloud.githubusercontent.com/assets/70312/8762908/13bcc08a-2d5d-11e5-9d93-eea710265334.png">

Here's the console output.

<img width="397" alt="screen shot 2015-07-18 at 2 55 09 pm" src="https://cloud.githubusercontent.com/assets/70312/8762909/166235f4-2d5d-11e5-9086-466f78ddcbfb.png">

I think the tests are broken (the mock code is mistakenly setting the error). Could you check in your own app with real requests whether this is true or not?

I think the solution is to actually rely on the status code, not on `urlSession.error`.

**Comment by wvteijlingen** [comment]
The `error` here points to a network error returned by the `NSURLSession`. If the API returns an 4xx status code, that means the request actually succeeded, so the error is nil. `NSURLSession` does not checking on status code whatsoever (that I know of at least).

**Comment by wvteijlingen** [comment]
I'm closing this issue in favour of the big error handling redesign issue.
