### ISSUE TITLE
Error/failure handling needs to be redesigned

### ISSUE THREAD

**Issue by kurko** [wvteijlingen/Spine#30]
So, I had a hard time figuring out how to return error messages so I can show them in the UI. After hours of debugging, the answer is we can't do it currently until we redesign the entire error handling logic.

This is the centralization for any work towards this goal.

- [ ] **4xx-5xx aren't handled at all**

  Currently, only network errors are being handled; everything else triggers `.onSuccess` (even `4xx` responses) https://github.com/wvteijlingen/Spine/issues/27

  I have a fix for this in a PR, but it's impossible to unit test without a big rewrite in the `CallbackHTTPClient` object, which completely replaces the `Networking` object in tests. Instead of stubbing the server, it's stubbing the client.

  To get make this rewrite not needed, we have to handle errors inside `Operations`. I believe that'd be correct because a `4xx` is not an error, it's just a decline from the server in the API negotiation. An error is an exception, such as a network error. 

- [ ] **Expose error response to `.onFailure` block**

  Given the expectations inside the code, there's no way to return response body all the way up and expose it in the `.onFailure` block. I need to show error messages in the UI, but I can't.

  We need to stop returning NSError from Networking and return our own error object, one that supports not just error code (e.g `4xx`), but the entire JSON response (not string, actual dictionary) and the JSONAPI standard.

  For example, in my code, inside `Networking`'s `performRequest()`, I tried something like the following, 

  ```swift
  var serializationErr: NSError?
  var jsonResult = NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions.MutableContainers, error: &serializationErr) as! NSDictionary

  // Trying to cramp jsonResult inside userInfo...
  let userInfo = [NSLocalizedFailureReasonErrorKey: jsonResult]
  operationError = NSError(domain: SpineServerErrorDomain, code: response!.statusCode, userInfo: userInfo)
  ```

  Inside my `.onFailure` block, I was able to output the dictionary above,
  
  ```
  println(error.userInfo)
  Optional([NSLocalizedFailureReason: {
      errors =     (
                  {
              code = 11001;
              source =             {
                  pointer = "/data/attributes/email";
              };
              title = "Value not specified.";
          }
      );
  }])
  ```

  However, when calling `println(error.localizedFailureReason)`, I get `-[__NSDictionaryI length]: unrecognized selector sent to instance 0x7ffd148788c0` because clearly a `String` was expected, not a dictionary.

**Comment by wvteijlingen** [comment]
I've started refactoring the response handling in the new swift-2.0 branch. It's a little more complicated than I anticipated because failure can happen in multiple places. I think to get this right it's absolutely necessary to have good tests for this.

The basic flow is now as follows: 
![screen shot 2015-10-12 at 20 55 06](https://cloud.githubusercontent.com/assets/1460535/10435946/917fce04-7123-11e5-80f2-db86ac27c2bf.png)

**Comment by wvteijlingen** [comment]
A sneak peak of the error handling as it is in the swift-2.0 branch right now:

- If an error occurs in the network, the future fails with a network NSError.
- If an error occurs in Spine (deserialising error), the future fails with a `SpineClientErrorDomain` NSError.
- If an error occurs in the API (http error), the future fails with a `SpineServerErrorDomain` NSError that has the HTTP error code. Its `userInfo` dictionary contains a key `apiErrors` which holds an array of errors that were returned in the JSONAPI document.

I think this provides a good basis and allows developers to handle each specific error separately based on the error domain and code.

**Comment by kurko** [comment]
Perfect.

**Comment by wvteijlingen** [comment]
This has been tackled in the Swift 2.0 version which I just merged into master. Thanks for the help!

**Comment by kurko** [comment]
No, thank you for the awesome work!
