### ISSUE TITLE
Nested resource - design question

### ISSUE THREAD

**Issue by FreakTheMighty** [wvteijlingen/Spine#31]
I'm wading into a a Java implementation and I'm curious what your `findOne` or `find` interface looks like for nested URLs. For example when fetch `/articles/1/author `, as found in [this section](http://jsonapi.org/format/#fetching-resources), how do you call `findOne` such that you fetch the author from article 1?

**Comment by wvteijlingen** [comment]
If my memory serves me correctly, this is a two step process which is not automated. First you have to do a `findOne` for `articles/1`. The returned resource will have `Resource` (to-one) or `LinkedResourceCollection` (to-many) objects for it's relationships fields. If the related resources were not sideloaded, these only include the URLs and optionally IDs.

If you then want to load these related resources you can create a Query for that resource or that collection and load them using the `find` or `findOne` methods that take a query. For to-one relationships you can also use the `ensure` method.

**Comment by FreakTheMighty** [comment]
Awesome, thanks for the information.
