### ISSUE TITLE
Swift 2.0?

### ISSUE THREAD

**Issue by lordmortis** [wvteijlingen/Spine#33]
I had a stab at getting this library going in Swift 2.0, but I don't understand enough of how it uses BrightFutures (the API of which has changed dramatically in the last few months it seems) to get it all going again. 

Any idea when you will get it going in Swift 2.0?

**Comment by wvteijlingen** [comment]
The plan is to convert to Swift 2 at some point, but unfortunately I'm very busy for at least the next few weeks. I don't know what breaking changes in BrightFuture we're looking at, but I image it shouldn't be that hard to fix. Spine mainly uses futures in its public interface.

**Comment by fedtuck** [comment]
Hi, does anybody know if there will be a swift 2.0 update?

**Comment by kurko** [comment]
@lordmortis do you have your fork somewhere? I'm going to try to convert it.

**Comment by wvteijlingen** [comment]
I started work on migrating the library but I'm running into a lot of issues. I believe a lot of these issues are due to using the `ResourceProtocol` as a generic. Most of the other changes in third-party libraries and the new syntax are trivial.

I'm currently thinking about dropping the protocol and just providing a base class. Perhaps we can add it later once we got the core of this lib to Swift 2.  Unfortunately this prevents other developers from using their own base class in the meantime.

What do you guys think?

**Comment by kurko** [comment]
I agree, @wvteijlingen. I can't think from the top of my mind why people wouldn't be able to extend/descend/inherit this new base class and add their own functionality. As for the protocol, I think that if it's part of the roadmap to support that, people will understand that it's a compromise for the better.

**Comment by kurko** [comment]
In the README, it states for Cocoapods:

> Add pod 'Spine', :git => 'https://github.com/wvteijlingen/Spine.git', :branch => 'swift-2.0' to your Podfile. The spec is not yet registered with the Cocoapods repository, because the library is still in flux.

I tried all sorts of combinations (tag/commit etc) to get the `swift-2.0` branch locally in my app but couldn't.

```
→ pod install
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `Spine` from `https://github.com/wvteijlingen/Spine.git`, branch `swift-2.0`, commit `ca05706b8480655076a131a34d9cccb1aa0d975d`, tag `swift-2.0`
[!] Unable to find a specification for 'Spine'.

[!] Unable to load a podspec from `Spine.podspec`, skipping:

Pod::DSLError
```

Any idea how could I try it locally with Cocoapods?

**Comment by sahin** [comment]
+1

**Comment by wvteijlingen** [comment]
The Swift 2.0 branch is merged into master.

**Comment by kurko** [comment]
:clap:
