### ISSUE TITLE
Relationship not included in payload on PUT

### ISSUE THREAD

**Issue by kurko** [wvteijlingen/Spine#35]
## Problem

Relationships are not being included in payloads when the request is an update (`PUT`). If the request is a creation (`POST`), the relationship hash is included normally.

**Expected behavior:** relationships should be included on both POST and PUT.

## Example

Given a `Post` resource that has a `Category` (`dynamic public var category: Category?`).

```swift
spine.registerResource(Post.resourceType) { Post() }
spine.registerResource(Category.resourceType) { Category() }

var category = Category()
category.id   = "some-uuid"
category.name = "Swift"

var post = Post()
post.id     = "uuid-id"
post.title   = "title"
post.body  = "body"
post.category = category

spine.save(post)
```

In the case above, a `PUT` operation takes place because `id` was set. `data.relationships` is **NOT** included in the call.

If we remove `post.id = "uuid-id"`, then a `POST` operation will take place and with that, `data.relationships` **is** included in the payload.

***

I could very well tackle this issue but I have 5 PRs opened right now and I'd need to know if you'd accept this before starting, specially given the Swift 2 effort.

**Comment by wvteijlingen** [comment]
The reason that relationships are not included on PUT requests is because we can't be sure whether a relationship has been fetched from the server in the first place. If you fetch a resource without relationship data, change an attribute and then save it with relationship data, the relationships would be overwritten with empty data (and thus lost).

**Comment by kurko** [comment]
Ok. I added `category_id` to my `data.attributes` to get it done (I own the server, so...). Not good but it'll work for now. As for client side ids, I agree, it's doing PUTs and I have to do some work on the server.

**Comment by wvteijlingen** [comment]
I'm closing this issue in favour of the Client side ids issue: https://github.com/wvteijlingen/Spine/issues/37. When client side ids are implemented, this should be resolved as well.
