### ISSUE TITLE
Error using Carthage

### ISSUE THREAD

**Issue by mt81** [wvteijlingen/Spine#40]
Adding github "wvteijlingen/Spine" to the Cartfile and executing the ```carthage update``` command, the result is: ```No tagged versions found for github "wvteijlingen/Spine"```

As workaround I have used ```github "wvteijlingen/Spine" "master"```

**Comment by wvteijlingen** [comment]
This is as expected because there are no tags yet. Thanks for letting me know though, I'll update the readme.
