### ISSUE TITLE
Pagination initializers

### ISSUE THREAD

**Issue by bonroyage** [wvteijlingen/Spine#45]
Hi,

I get an error when I try to add pagination to my query.

The following code:
```swift
var query = Query(resourceType: Post.self)
query.paginate(OffsetBasedPagination(offset: 0, limit: 5))
```

results in the following error:

`'OffsetBasedPagination' cannot be constructed because it has no accessible initializers`

I have tried adding the initializer to struct myself but it doesn't seem to make a difference.

Cheers!

**Comment by wvteijlingen** [comment]
Ah yes, default memberwise initialisers are internal by default. I've added the public initialisers.
