### ISSUE TITLE
Bool instead of NSNumber

### ISSUE THREAD

**Issue by xamoom-raphael** [wvteijlingen/Spine#51]
Hey,
I'm just started using Spine and I wonder if it is possible to use native Bool instead of NSNumber?

ATM it looks like this:
```swift
  dynamic var demo: NSNumber?
```

**Comment by xamoom-raphael** [comment]
I'm very sorry, I made a mistake in my api, so I did not receive the complete json.
It's no problem to map a Bool like:

```swift
var demo : Bool = false
```

Can be closed.

**Comment by wvteijlingen** [comment]
You can indeed use value types like Bool, Int, Float etc. The caveat though is that you _cannot_ mark them as optionals. Unfortunately this is downside of using Key Value Coding.
