### ISSUE TITLE
Complex attributes with subobject

### ISSUE THREAD

**Issue by Alak** [wvteijlingen/Spine#64]
Hey,

I'm wondering if there is a way to parse subobject in attributes like : 

```
{
    "data": {
        "type": "posts",
        "id": "671",
        "attributes": {
            "id": 671,
            "title": "funy place",
            "location": {
                "name": "La Sorbonne, Paris",
                "short_name": "La Sorbonne",
                "latitude": 52.377965,
                "longitude": 4.912809,
                "distance_from_me": 9125000
            }
        }
    }
}
```

Thanks

**Comment by wvteijlingen** [comment]
This should be possible using a custom attribute type and matching formatter. It depends on how you want to represent the nested data in your client. It should be something like this:

```swift
class LocationAttribute: Attribute {}

struct  LocationValueFormatter: ValueFormatter {
	func unformat(value: AnyObject, attribute: LocationAttribute) ->  AnyObject {
		// Convert from serialised form to deserialised form
	}
	
	func format(value: AnyObject, attribute: LocationAttribute) -> AnyObject {
		// Convert from deserialised form to serialised form
	}
}

spine.registerValueFormatter(LocationValueFormatter())
```

**Comment by Alak** [comment]
Thanks, perfect

**Comment by wvteijlingen** [comment]
Cool, let me know if there's any trouble :).

**Comment by gbejarano01** [comment]
@wvteijlingen I'm trying something like this but it's not working.

Let's say in this case I'm creating a custom Object "Location" with all the properties from location node in the json.

Then when I declare the type of location it's "Location" so when you define unformat it's returning an object "Location" and when defining format the parameter is type "Location" and returns String.

I'm getting a message:

this class is not key value coding-compliant for the key location

**Comment by gbejarano01** [comment]
@Alak Did this work for you?

**Comment by gbejarano01** [comment]
I think I fixed it, by declaring the property as AnyObject, the problem is when you want to use the property you have to unwrap it as the type you need.

**Comment by wvteijlingen** [comment]
What kind of type is `Location`?

**Comment by gbejarano01** [comment]
Location should be a custom Class called Location that contains all the properties of the location node in the Json file.

I could fix this, the only issue is that is not letting me declare that as a Location property in my Resource Object, I need to declare it as AnyObject, otherwise I get:

`this class is not key value coding-compliant for the key location`

**Comment by YoussefMostafa** [comment]
@wvteijlingen 
if we have array of locations ... how we can parse it in custom attribute ? .. 
{
  "location": [
           {
                "name": "La Sorbonne, Paris",
                "short_name": "La Sorbonne",
                "latitude": 52.377965,
                "longitude": 4.912809,
                "distance_from_me": 9125000
            },
           {
                "name": "La Sorbonne, Paris",
                "short_name": "La Sorbonne",
                "latitude": 52.377965,
                "longitude": 4.912809,
                "distance_from_me": 9125000
            }
              ]
}

**Comment by YoussefMostafa** [comment]
@gbejarano01  
did you manage to fix this problem ?
