### ISSUE TITLE
Tag some (semantically-versioned) releases

### ISSUE THREAD

**Issue by cbowns** [wvteijlingen/Spine#67]
Hi! Could you start tagging releases with [SemVer](http://semver.org) for library clients who use things like Cocoapods to have stable version tags to point to? I noticed we were on the `swift-2.0` branch, and now that that's on `master`, I'd love to point to something more stable than the SHA du jour.

**Comment by wvteijlingen** [comment]
Hi Christopher, you're right, the library is at a point now that I can at least start tagging 0.x releases. I'd like to hold off a 1.0 release until proper tests have been written for everything. I'm merging in some changes soon and will create a release asap.

**Comment by cbowns** [comment]
Sounds great, thank you!
