### ISSUE TITLE
Show network activity indicator while loading

### ISSUE THREAD

**Issue by davidgoli** [wvteijlingen/Spine#71]
This is a nice-to-have. Currently we can explicitly call `UIApplication.sharedApplication().networkActivityIndicatorVisible = true` before/after each request, but that becomes cumbersome and clutters the codebase with boilerplate. The preferred option is to just provide a boolean to toggle this behavior on/off globally for the `Spine` instance or the `HTTPClient` instance. Another option is to provide a hook in `HTTPClient` for request began/ended so that we could implement this ourselves and/or possibly other behaviors around network activity.

**Comment by wvteijlingen** [comment]
Nice idea. I think the best way to implement such a thing would be to create hooks, as you mentioned. This allows you to add any kind of functionality that depends on network activity. Perhaps we can add a delegate to the standard HTTPClient. Custom NetworkClients can implement delegates or hooks themselves.

**Comment by wvteijlingen** [comment]
What do you think about the following:

```swift
@objc protocol HTTPClientDelegate {
	optional func willPerformRequestWithMethod(method: String, URL: NSURL, payload: NSData?)
	optional func didPerformRequestWithMethod(method: String, URL: NSURL, success: Bool)
}
```

**Comment by wvteijlingen** [comment]
I've added a HTTPClientDelegate protocol to the built in HTTPClient. You can use this to implement such functionality. Custom NetworkClients can incorporate their own delegate protocol.

**Comment by davidgoli** [comment]
Sounds great, thank you!
