### ISSUE TITLE
Serializer should not fail when top level "data" attribute is present but nil

### ISSUE THREAD

**Issue by richardmcclellan** [wvteijlingen/Spine#77]
I am currently using a API that returns the following response:
```
{
	"data": null
}
```
According to the [JSONAPI spec](http://jsonapi.org/format/#document-top-level), this is a valid format, but Spine returns the following serializer error:
`Either 'data', 'errors', or 'meta' must be present in the top level.`

**Comment by wvteijlingen** [comment]
I merged your PR that fixes this. Thanks for contributing!
