### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by invliD** [wvteijlingen/Spine#91]

**Comment by Blackjacx** [comment]
We want too 👍

**Comment by Blackjacx** [comment]
Do you have a plan when you migrate your code to Swift 3 or Swift 2.3? Since Xcode 8 is out now we would like to switch as fast as possible.

**Comment by wvteijlingen** [comment]
Check out the swift-3.0 branch: https://github.com/wvteijlingen/Spine/tree/swift-3.0

**Comment by waritsan** [comment]
swift-3.0 branch does not work for me. Here are a few points to look at

1. It does not work with Cocoapod. There's a typo in podspec #107 
2. SwiftyJSON dependency is not swift 3 compatible.
3. After manually fixing the above issues, there are syntax errors so I use the auto conversion. I was able to build successfully but I got a runtime error.

Has anyone got it to work? Please advise.

**Comment by wvteijlingen** [comment]
I updated the Podspec to remove the extraneous apostrophe. I'm no Cocoapods user but I believe you need to point to the SwiftyJSON swift 3 branch in your own Podfile.

Regarding the syntax issues, could you create a PR for them or let me know which issues there are? Thanks!

**Comment by Blackjacx** [comment]
Hey, 

to use the Swift 3 branch as dependency for your POD you need to specify that in the podspec of Spine in its Swift 3 branch. With Cocoapods always the pod owner is responsible for setting the correct dependencies.

**Comment by wvteijlingen** [comment]
If I am not mistaken Cocoapods does not allow you specify unreleased pod versions in a Podspec. See https://github.com/cocoapods/cocoapods/issues/3901#issuecomment-227291635. Again, I'm not a Cocoapods user so if you have a fix for this, feel free to create a PR.

**Comment by waritsan** [comment]
Right, you can't specify a dependency as git repo in podspec. In that case you might want to update the installation guide for cocoapod with the following line. It works for me.

`pod 'SwiftyJSON', :git => 'https://github.com/appsailor/SwiftyJSON.git', :branch => 'swift3'`

Thanks,

**Comment by Blackjacx** [comment]
Ahhh nice thank you!
