### ISSUE TITLE
Ability to use `FetchOperation` directly.

### ISSUE THREAD

**Issue by markst** [wvteijlingen/Spine#96]
We'd like to be able to use `FetchOperation` directly, to enable us to cancel previous operations.

```swift
//Cancel previous operation
self.operation.cancel()

//
self.operation = FetchOperation(query: query, spine: self)
self.operation.completionBlock = { [unowned operation] in
....
self.operation.start()
```

**Comment by wvteijlingen** [comment]
I think it's better to keep the operation itself an implementation detail. Making it a public API will make it much harder to refactor inner workings if needed. Luckily the `FetchOperation` class is pretty simple, you it should be easy for you to create your own `NSOperation` subclass that does the work.

**Comment by markst** [comment]
Thanks for response @wvteijlingen.
I'm in the process of having to create my own operation.
It would be good to be able to subclass from `ConcurrentOperation`, however this doesn't seem to be possible due to:
![image](https://cloud.githubusercontent.com/assets/274318/23980328/300089a0-0a53-11e7-884c-b77f18a9019d.png)

Even if subclassing from `NSOperation` it would be good if Spine's `Failable` was public also.
